#include <SDL2/SDL_image.h>

#define SDL_IMAGE_FLAGS		IMG_INIT_JPG | IMG_INIT_PNG | IMG_INIT_TIF | IMG_INIT_WEBP | IMG_INIT_JXL | IMG_INIT_AVIF
#define SDL_FLAGS					SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC

